export const GET_CHAT_REQUEST = 'GET_CHAT_REQUEST'
export const GET_CHAT_SUCCESS = 'GET_CHAT_SUCCESS'
export const GET_CHAT_FAIL = 'GET_CHAT_FAIL'
export const GET_CHAT_RESET = 'GET_CHAT_RESET'

export const NEW_CHAT_REQUEST = 'NEW_CHAT_REQUEST'
export const NEW_CHAT_SUCCESS = 'NEW_CHAT_SUCCESS'
export const NEW_CHAT_RESET = 'NEW_CHAT_RESET'
export const NEW_CHAT_FAIL = 'NEW_CHAT_FAIL'

export const UPDATE_CHAT_REQUEST = 'UPDATE_CHAT_REQUEST'
export const UPDATE_CHAT_SUCCESS = 'UPDATE_CHAT_SUCCESS'
export const UPDATE_CHAT_RESET = 'UPDATE_CHAT_RESET'
export const UPDATE_CHAT_FAIL = 'UPDATE_CHAT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'