export const TODAY_COLLECTION_POINT_LIST_REQUEST = 'TODAY_COLLECTION_POINT_LIST_REQUEST'
export const TODAY_COLLECTION_POINT_LIST_SUCCESS = 'TODAY_COLLECTION_POINT_LIST_SUCCESS'
export const TODAY_COLLECTION_POINT_LIST_FAIL = 'TODAY_COLLECTION_POINT_LIST_FAIL'

export const UPCOMING_COLLECTION_POINT_LIST_REQUEST = 'UPCOMING_COLLECTION_POINT_LIST_REQUEST'
export const UPCOMING_COLLECTION_POINT_LIST_SUCCESS = 'UPCOMING_COLLECTION_POINT_LIST_SUCCESS'
export const UPCOMING_COLLECTION_POINT_LIST_FAIL = 'UPCOMING_COLLECTION_POINT_LIST_FAIL'

export const COLLECTION_POINT_LIST_REQUEST = 'COLLECTION_POINT_LIST_REQUEST'
export const COLLECTION_POINT_LIST_SUCCESS = 'COLLECTION_POINT_LIST_SUCCESS'
export const COLLECTION_POINT_LIST_FAIL = 'COLLECTION_POINT_LIST_FAIL'

export const ALL_COLLECTORS_REQUEST = 'ALL_COLLECTORS_REQUEST'
export const ALL_COLLECTORS_SUCCESS = 'ALL_COLLECTORS_SUCCESS'
export const ALL_COLLECTORS_FAIL = 'ALL_COLLECTORS_FAIL'
export const ALL_COLLECTORS_RESET = 'ALL_COLLECTORS_RESET'

export const ALL_COLLECTION_POINTS_REQUEST = 'ALL_COLLECTION_POINTS_REQUEST'
export const ALL_COLLECTION_POINTS_SUCCESS = 'ALL_COLLECTION_POINTS_SUCCESS'
export const ALL_COLLECTION_POINTS_FAIL = 'ALL_COLLECTION_POINTS_FAIL'

export const COLLECTION_POINT_DETAILS_REQUEST = 'COLLECTION_POINT_DETAILS_REQUEST' 
export const COLLECTION_POINT_DETAILS_SUCCESS = 'COLLECTION_POINT_DETAILS_SUCCESS'
export const COLLECTION_POINT_DETAILS_FAIL = 'COLLECTION_POINT_DETAILS_FAIL'

export const NEW_COLLECTION_POINT_REQUEST = 'NEW_COLLECTION_POINT_REQUEST'
export const NEW_COLLECTION_POINT_SUCCESS = 'NEW_COLLECTION_POINT_SUCCESS'
export const NEW_COLLECTION_POINT_RESET = 'NEW_COLLECTION_POINT_RESET'
export const NEW_COLLECTION_POINT_FAIL = 'NEW_COLLECTION_POINT_FAIL'

export const UPDATE_COLLECTION_POINT_REQUEST = 'UPDATE_COLLECTION_POINT_REQUEST'
export const UPDATE_COLLECTION_POINT_SUCCESS = 'UPDATE_COLLECTION_POINT_SUCCESS'
export const UPDATE_COLLECTION_POINT_RESET = 'UPDATE_COLLECTION_POINT_RESET'
export const UPDATE_COLLECTION_POINT_FAIL = 'UPDATE_COLLECTION_POINT_FAIL'

export const DELETE_COLLECTION_POINT_REQUEST = 'DELETE_COLLECTION_POINT_REQUEST'
export const DELETE_COLLECTION_POINT_SUCCESS = 'DELETE_COLLECTION_POINT_SUCCESS'
export const DELETE_COLLECTION_POINT_RESET = 'DELETE_COLLECTION_POINT_RESET'
export const DELETE_COLLECTION_POINT_FAIL = 'DELETE_COLLECTION_POINT_FAIL'

export const ADD_COLLECTION_NUMBER_OF_TRUCK_REQUEST = 'ADD_COLLECTION_NUMBER_OF_TRUCK_REQUEST'
export const ADD_COLLECTION_NUMBER_OF_TRUCK_SUCCESS = 'ADD_COLLECTION_NUMBER_OF_TRUCK_SUCCESS'
export const ADD_COLLECTION_NUMBER_OF_TRUCK_RESET = 'ADD_COLLECTION_NUMBER_OF_TRUCK_RESET'
export const ADD_COLLECTION_NUMBER_OF_TRUCK_FAIL = 'ADD_COLLECTION_NUMBER_OF_TRUCK_FAIL'

export const LIVE_NOTIFICATION_REQUEST = 'LIVE_NOTIFICATION_REQUEST'
export const LIVE_NOTIFICATION_SUCCESS = 'LIVE_NOTIFICATION_SUCCESS'
export const LIVE_NOTIFICATION_RESET = 'LIVE_NOTIFICATION_RESET'
export const LIVE_NOTIFICATION_FAIL = 'LIVE_NOTIFICATION_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'