export const NEW_FEEDBACK_REQUEST = 'NEW_FEEDBACK_REQUEST'
export const NEW_FEEDBACK_SUCCESS = 'NEW_FEEDBACK_SUCCESS'
export const NEW_FEEDBACK_RESET = 'NEW_FEEDBACK_RESET'
export const NEW_FEEDBACK_FAIL = 'NEW_FEEDBACK_FAIL'

export const GET_FEEDBACK_REQUEST = 'GET_FEEDBACK_REQUEST'
export const GET_FEEDBACK_SUCCESS = 'GET_FEEDBACK_SUCCESS'
export const GET_FEEDBACK_FAIL = 'GET_FEEDBACK_FAIL'
export const GET_FEEDBACK_RESET = 'GET_FEEDBACK_RESET'


export const GET_FEEDBACKS_REQUEST = 'GET_FEEDBACKS_REQUEST'
export const GET_FEEDBACKS_SUCCESS = 'GET_FEEDBACKS_SUCCESS'
export const GET_FEEDBACKS_FAIL = 'GET_FEEDBACKS_FAIL'
export const GET_FEEDBACKS_RESET = 'GET_FEEDBACKS_RESET'


export const GET_USER_FEEDBACKS_REQUEST = 'GET_USER_FEEDBACKS_REQUEST'
export const GET_USER_FEEDBACKS_SUCCESS = 'GET_USER_FEEDBACKS_SUCCESS'
export const GET_USER_FEEDBACKS_FAIL = 'GET_USER_FEEDBACKS_FAIL'
export const GET_USER_FEEDBACKS_RESET = 'GET_USER_FEEDBACKS_RESET'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'