export const ITEM_LIST_REQUEST = 'ITEM_LIST_REQUEST'
export const ITEM_LIST_SUCCESS = 'ITEM_LIST_SUCCESS'
export const ITEM_LIST_FAIL = 'ITEM_LIST_FAIL'

export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST'
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS'
export const ADD_ITEM_RESET = 'ADD_ITEM_RESET'
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL'

export const CLAIM_ITEM_REQUEST = 'CLAIM_ITEM_REQUEST'
export const CLAIM_ITEM_SUCCESS = 'CLAIM_ITEM_SUCCESS'
export const CLAIM_ITEM_RESET = 'CLAIM_ITEM_RESET'
export const CLAIM_ITEM_FAIL = 'CLAIM_ITEM_FAIL'

export const CANCEL_ITEM_REQUEST = 'CANCEL_ITEM_REQUEST'
export const CANCEL_ITEM_SUCCESS = 'CANCEL_ITEM_SUCCESS'
export const CANCEL_ITEM_RESET = 'CANCEL_ITEM_RESET'
export const CANCEL_ITEM_FAIL = 'CANCEL_ITEM_FAIL'

export const CONFIRM_ITEM_REQUEST = 'CONFIRM_ITEM_REQUEST'
export const CONFIRM_ITEM_SUCCESS = 'CONFIRM_ITEM_SUCCESS'
export const CONFIRM_ITEM_RESET = 'CONFIRM_ITEM_RESET'
export const CONFIRM_ITEM_FAIL = 'CONFIRM_ITEM_FAIL'

export const RECEIVE_ITEM_REQUEST = 'RECEIVE_ITEM_REQUEST'
export const RECEIVE_ITEM_SUCCESS = 'RECEIVE_ITEM_SUCCESS'
export const RECEIVE_ITEM_RESET = 'RECEIVE_ITEM_RESET'
export const RECEIVE_ITEM_FAIL = 'RECEIVE_ITEM_FAIL'

export const ALL_ITEMS_REQUEST = 'ALL_ITEMS_REQUEST'
export const ALL_ITEMS_SUCCESS = 'ALL_ITEMS_SUCCESS'
export const ALL_ITEMS_FAIL = 'ALL_ITEMS_FAIL'

export const ITEM_DETAILS_REQUEST = 'ITEM_DETAILS_REQUEST' 
export const ITEM_DETAILS_SUCCESS = 'ITEM_DETAILS_SUCCESS'
export const ITEM_DETAILS_FAIL = 'ITEM_DETAILS_FAIL'

export const NEW_ITEM_REQUEST = 'NEW_ITEM_REQUEST'
export const NEW_ITEM_SUCCESS = 'NEW_ITEM_SUCCESS'
export const NEW_ITEM_RESET = 'NEW_ITEM_RESET'
export const NEW_ITEM_FAIL = 'NEW_ITEM_FAIL'

export const UPDATE_ITEM_REQUEST = 'UPDATE_ITEM_REQUEST'
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS'
export const UPDATE_ITEM_RESET = 'UPDATE_ITEM_RESET'
export const UPDATE_ITEM_FAIL = 'UPDATE_ITEM_FAIL'

export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST'
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS'
export const DELETE_ITEM_RESET = 'DELETE_ITEM_RESET'
export const DELETE_ITEM_FAIL = 'DELETE_ITEM_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'