export const NEWSFEED_LIST_REQUEST = 'NEWSFEED_LIST_REQUEST'
export const NEWSFEED_LIST_SUCCESS = 'NEWSFEED_LIST_SUCCESS'
export const NEWSFEED_LIST_FAIL = 'NEWSFEED_LIST_FAIL'

export const ALL_NEWSFEEDS_REQUEST = 'ALL_NEWSFEEDS_REQUEST'
export const ALL_NEWSFEEDS_SUCCESS = 'ALL_NEWSFEEDS_SUCCESS'
export const ALL_NEWSFEEDS_FAIL = 'ALL_NEWSFEEDS_FAIL'

export const NEWSFEED_DETAILS_REQUEST = 'NEWSFEED_DETAILS_REQUEST' 
export const NEWSFEED_DETAILS_SUCCESS = 'NEWSFEED_DETAILS_SUCCESS'
export const NEWSFEED_DETAILS_FAIL = 'NEWSFEED_DETAILS_FAIL'

export const NEW_NEWSFEED_REQUEST = 'NEW_NEWSFEED_REQUEST'
export const NEW_NEWSFEED_SUCCESS = 'NEW_NEWSFEED_SUCCESS'
export const NEW_NEWSFEED_RESET = 'NEW_NEWSFEED_RESET'
export const NEW_NEWSFEED_FAIL = 'NEW_NEWSFEED_FAIL'

export const UPDATE_NEWSFEED_REQUEST = 'UPDATE_NEWSFEED_REQUEST'
export const UPDATE_NEWSFEED_SUCCESS = 'UPDATE_NEWSFEED_SUCCESS'
export const UPDATE_NEWSFEED_RESET = 'UPDATE_NEWSFEED_RESET'
export const UPDATE_NEWSFEED_FAIL = 'UPDATE_NEWSFEED_FAIL'

export const DELETE_NEWSFEED_REQUEST = 'DELETE_NEWSFEED_REQUEST'
export const DELETE_NEWSFEED_SUCCESS = 'DELETE_NEWSFEED_SUCCESS'
export const DELETE_NEWSFEED_RESET = 'DELETE_NEWSFEED_RESET'
export const DELETE_NEWSFEED_FAIL = 'DELETE_NEWSFEED_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'