// export const SOCKET_PORT = 'https://basurahunt.herokuapp.com/'
// export const SOCKET_PORT = 'http://localhost:3001'
// export const SOCKET_PORT = 'http://127.0.0.1:3001'
// export const SOCKET_PORT = 'https://basurahuntsocket.herokuapp.com/'
export const SOCKET_PORT = 'https://basurahunt-socket.onrender.com/'
