export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const FIND_EMAIL_REQUEST = 'FIND_EMAIL_REQUEST'
export const FIND_EMAIL_SUCCESS = 'FIND_EMAIL_SUCCESS'
export const FIND_EMAIL_FAIL = 'FIND_EMAIL_FAIL'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const REFRESH_OTP_REQUEST = 'REFRESH_OTP_REQUEST'
export const REFRESH_OTP_SUCCESS = 'REFRESH_OTP_SUCCESS'
export const REFRESH_OTP_FAIL = 'REFRESH_OTP_FAIL'

export const CHECK_OTP_REQUEST = 'CHECK_OTP_REQUEST'
export const CHECK_OTP_SUCCESS = 'CHECK_OTP_SUCCESS' 
export const CHECK_OTP_FAIL = 'CHECK_OTP_FAIL'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET'
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'


export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'
export const FORGOT_PASSWORD_RESET = 'FORGOT_PASSWORD_RESET'

export const NEW_PASSWORD_REQUEST = 'NEW_PASSWORD_REQUEST'
export const NEW_PASSWORD_SUCCESS = 'NEW_PASSWORD_SUCCESS'
export const NEW_PASSWORD_FAIL = 'NEW_PASSWORD_FAIL'
export const NEW_PASSWORD_RESET = 'NEW_PASSWORD_RESET'

export const ALL_USERS_REQUEST = 'ALL_USERS_REQUEST'
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS'
export const ALL_USERS_FAIL = 'ALL_USERS_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_RESET = 'DELETE_USER_RESET'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'

export const USER_DUMPS_REQUEST = 'USER_DUMPS_REQUEST'
export const USER_DUMPS_SUCCESS = 'USER_DUMPS_SUCCESS'
export const USER_DUMPS_FAIL = 'USER_DUMPS_FAIL'

export const USER_CLAIMED_REQUEST = 'USER_CLAIMED_REQUEST'
export const USER_CLAIMED_SUCCESS = 'USER_CLAIMED_SUCCESS'
export const USER_CLAIMED_FAIL = 'USER_CLAIMED_FAIL'

export const USER_RECEIVE_REQUEST = 'USER_RECEIVE_REQUEST'
export const USER_RECEIVE_SUCCESS = 'USER_RECEIVE_SUCCESS'
export const USER_RECEIVE_FAIL = 'USER_RECEIVE_FAIL'

export const USER_DONATED_REQUEST = 'USER_DONATED_REQUEST'
export const USER_DONATED_SUCCESS = 'USER_DONATED_SUCCESS'
export const USER_DONATED_FAIL = 'USER_DONATED_FAIL'

export const READ_NOTIFICATION_REQUEST = 'READ_NOTIFICATION_REQUEST'
export const READ_NOTIFICATION_SUCCESS = 'READ_NOTIFICATION_SUCCESS'
export const READ_NOTIFICATION_RESET = 'READ_NOTIFICATION_RESET'
export const READ_NOTIFICATION_FAIL = 'READ_NOTIFICATION_FAIL'

export const GET_LEVEL_EXP_REQUEST = 'GET_LEVEL_EXP_REQUEST'
export const GET_LEVEL_EXP_SUCCESS = 'GET_LEVEL_EXP_SUCCESS'
export const GET_LEVEL_EXP_RESET = 'GET_LEVEL_EXP_RESET'
export const GET_LEVEL_EXP_FAIL = 'GET_LEVEL_EXP_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'